version: '3.8'

services:
  web:
    build: .
    command: bash -c "sleep 15 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - shared_network  # Adiciona a rede compartilhada
      - my_shared_network

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: pagamentos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    networks:
      - shared_network  # Adiciona a rede compartilhada

volumes:
  postgres_data:

networks:
  shared_network:
    driver: bridge
  my_shared_network:
    external: true
