# Generated by Django 5.2.4 on 2025-07-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='ID externo')),
                ('payment_type', models.CharField(choices=[('PIX', 'Pix'), ('CREDIT_CARD', 'Cartão de crédito')], max_length=50, verbose_name='Tipo do pagamento')),
                ('link_payment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link do pagamento')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('status', models.CharField(choices=[('pending', 'Aguardando pagamento'), ('completed', 'Pagamento concluído'), ('canceled', 'Pagamento Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('user_id', models.IntegerField(verbose_name='ID do Usuário')),
                ('id_order', models.IntegerField(blank=True, null=True, verbose_name='ID do Pedido')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
            },
        ),
    ]
