# Generated by Django 5.2.4 on 2025-08-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='user_cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF do Usuário'),
        ),
    ]
